cache:
  - C:\Users\appveyor\.tools

init:
  - git config --global core.autocrlf true

clone_depth: 50

skip_commits:
  files:
    - 'documentation/*'
    - '**/*.html'
    - '**/*.md'
    - '.travis.yml'

# Build Configurations: dll/static, regular/debug
configuration:
  - dynamic
  - static
  - dynamic-debug
  - static-debug

environment:
  # common / default variables for all jobs
  SETUP_PATH: .ci-local

  matrix:
  - CMP: vs2019
    BASE: 7.0
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

# Platform: processor architecture
platform:
  - x64

install:
  - cmd: git submodule update --init --recursive

build_script:
  - cmd: python .ci/cue.py prepare
  - cmd: python .ci/cue.py build

test_script:
  - cmd: python .ci/cue.py test

on_finish:
  - ps: Get-ChildItem *.tap -Recurse -Force | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - cmd: python .ci/cue.py test-results

notifications:
  - provider: GitHubPullRequest
