#---------------------
# Set up the Environment
#
TOP=..
include $(TOP)/configure/CONFIG

#---------------------
# Install include files
#
INC += epicsMMIO.h
INC += epicsMMIODef.h

#---------------------
# Generic EPICS build rules
#
include $(TOP)/configure/RULES
